### ISSUE TITLE
‘Estimated reading time’

### ISSUE THREAD

**Issue by sfuma888** [Yoast/duplicate-post#110] opened 2021-01-28 11:13 UTC
Not generated on old articles.
<meta name = “twitter: label2” content = “Reading time”>
![yoast](https://user-images.githubusercontent.com/78148025/106130787-da34ee00-6172-11eb-81bc-7c7b8d398597.jpg)

Sorry, wrote to the wrong heading!

**Comment by Djennez** [comment] 2021-01-28 11:48
Duplicate of https://github.com/Yoast/wordpress-seo/issues/16602

**Closed by Djennez** 2021-01-28 11:48 UTC
